In [1]:
import numpy as np

In [2]:
# Control Parameters
num_ants = 100
init_pheromone = 1
alpha = 1
beta = 1
rho = 0.1
Q = 5

In [6]:
Cordinates = [[0.0333692,0.9925079],[0.6020896,0.0168807],[0.1532083, 0.7020444],[0.3181124, 0.1469288],[0.1878440, 0.8679120],
[0.9786112, 0.4925364],[0.7918010, 0.7943144],[0.5145329, 0.0363478],[0.5500754, 0.8324617],[0.3893757, 0.6635483],[0.9641841, 0.6400201],
[0.7718126, 0.5463923],[0.7549037, 0.4584584],[0.2837881, 0.7733415],[0.3308411, 0.1974851],[0.7977221, 0.1193149],[0.3221207, 0.7930478],
[0.9201035, 0.1186234],[0.2397964, 0.1448552],[0.3967470, 0.6716172]]


In [7]:
print(np.shape(Cordinates))

(20, 2)


In [27]:
dist_matrix = np.zeros((20,20))
tabu_list = []
Prob_list = np.zeros((20))
Path_list = []
print(dist_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [28]:
num_cities = np.shape(Cordinates)[0]
#print(num_cities)
for i in range(0,num_cities):
    for j in range(0,num_cities):
        dist_matrix[i][j] = np.sqrt(np.power(Cordinates[i][0]-Cordinates[j][0],2) + np.power(Cordinates[i][1]-Cordinates[j][1],2))

In [29]:
#print(dist_matrix)

In [30]:
pheromone_matrix = np.ones((20,20))

In [32]:
for i in range(0,num_ants):
    init_node = int(np.random.uniform(0,20))
    Prob_list = np.zeros((20))
    Cum_Prob_list = np.zeros((20))
    tabu_list = np.ones((20))
    flag = 1
    while(flag):
        pheromone_distance_ratio = np.zeros((20))
        current_node = init_node
        tabu_list[current_node] = 0
        
      
        for j in range(0,20):
            if(tabu_list[j]!=0):
                pheromone_distance_ratio = (pheromone_matrix[current_node][j])/(distance_matrix[current_node][j])
                sum_p_d_ratio = np.sum(pheromone_distance_ratio)
                Prob_list[j] = pheromone_distance_ratio/sum_p_d_ratio
                Cum_Prob_list[j] += Prob_list[j]
        
        rand_selection = np.random.uniform()
        k = 0
        flag2 = 0
        next_node = 0
        while(flag2==0):
            if(rand_selection<Cum_Prob_list[k]):
                k = k+1
                next_node = k
        
        tabu_list[next_node] = 0
        flag = np.any(tabu_list)
    # Pheromone update
    

IndexError: list index out of range